# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Talks
tagline: by Moisés Guimarães
author: Moisés Guimarães de Medeiros
email: guimaraes+talks@pm.me
instagram: moguimar
facebook: guimaraes.moises
medium: moisesguimaraes
twitter: moisesguimaraes
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/talks" # the subpath of your site, e.g. /blog
url: "https://moisesguimaraes.com" # the base hostname & protocol for your site

collections:
  talks:
    output: true

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass
